### ISSUE TITLE
Revamp UI for better experience

### ISSUE THREAD

**Issue by omjogani** [The-Enthusiast-404/git-begin#5]
The current user interface is not very effective, which makes it difficult to use the existing filter function. I plan to improve it so it's easier to test and use the current features, and so it will work well with future updates.

**Comment by dotslashbit** [comment]
@omjogani Please add dark and light theme support if you can

**Comment by dotslashbit** [comment]
@omjogani Added another filter that'll let users search issues by frameworks or libraries like (reactjs, expressjs, flask, etc). If you have started working on the design, then please rebase it to main and design the whole thing. I'm not that good with design, that's why your contribution to design will be highly appreciated, take your time, no rush. We aren't launching it this Monday

**Comment by dotslashbit** [comment]
@omjogani I have deployed the web app, yay 🎉. Its a temporary move, will eventually get to cloudflare. It'll be awesome if you can give me an estimate on when you'll be able to open a PR for the UI.

**Comment by omjogani** [comment]
#10 

PR is merged, Closing this issue!
